/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Frontend": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "GameApi": {
      "type": "sst.aws.AppSync"
      "url": string
    }
    "GameApiDataSourceGameResolverFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GameRooms": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}