/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* biome-ignore-all lint: auto-generated */

/// <reference types="vite/client" />
interface ImportMetaEnv {
  readonly VITE_APPSYNC_URL: string
  readonly VITE_APPSYNC_API_KEY: string
}
interface ImportMeta {
  readonly env: ImportMetaEnv
}